const ActionNames = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GETPRODUCTALLLIST: "GETPRODUCTALLLIST",
  CREATEPRODUCTLIST: "CREATEPRODUCTLIST",
  UPDATEPRODUCT: "UPDATEPRODUCT",
  DELETEPRODUCT: "DELETEPRODUCT",
};

export default ActionNames;
